Fix test discrepancy
Doveps/mono pull request #139
Opened 2018-04-04 13:40 UTC by JosiahRegencia

2018-04-05 00:48 UTC, greenmoss commented on docker-compose.yml
> +    env_file: .env
We have to leave this commented

2018-04-05 00:49 UTC, greenmoss commented on .travis.yml
> +script: docker exec mono_savant_1 sh tests/db.sh
should this stay as the original?

2018-04-05 00:51 UTC, greenmoss commented on savant/app/get_scanned.py
> +    logging.debug('\nBeen to get_items')
better to remove `\n` from logging statements

2018-04-05 00:53 UTC, greenmoss commented on savant/app/get_scanned.py
> +    logging.debug('\n\File: {}\n\n'.format(filename))
for log statements, use commas for arguments

`debug('File: %s', filename)`

2018-04-05 00:54 UTC, greenmoss commented on savant/app/get_scanned.py
> +    logging.debug('\nDebs: {}'.format(debs))
same thing for commas here

2018-04-05 00:54 UTC, greenmoss commented on savant/app/get_scanned.py
> +    logging.debug('\nGroups: {}'.format(groups))
commas again

2018-04-05 00:54 UTC, greenmoss commented on savant/app/get_scanned.py
> +logging.basicConfig(level=logging.DEBUG, format='%(asctime)s : %(levelname)s : %(message)s')
default log level should be WARNING

2018-04-05 00:56 UTC, greenmoss commented on savant/app/query.py
> +        logging.basicConfig(level=logging.DEBUG, format='%(asctime)s : %(levelname)s : %(message)s')
`WARNING` ;)

2018-04-05 14:23 UTC, JosiahRegencia commented
I'm getting this from travis:
Error response from daemon: Container 9971df3bed5bb2bb7870d98ac81c2a6293928c94b40695880a643d81e3501844 is not running

![screenshot from 2018-04-05 22-22-38](https://user-images.githubusercontent.com/8079107/38371787-de0a5f70-391f-11e8-83fb-b53815bda293.png)

2018-04-05 14:43 UTC, JosiahRegencia commented
https://travis-ci.org/Doveps/mono/builds/362662427

2018-04-07 16:58 UTC, greenmoss requested changes

2018-04-07 16:58 UTC, greenmoss commented on savant/app/query.py
> +
Following up with the meeting last Wednesday:

Please transition testing to use only `GET` and `CREATE` API endpoints for the testing. Going that route, I am guessing we don't need `null_cases` or `count_rows`. The test instead does a `CREATE` that would have triggered the null condition, then does a `GET` to verify the count of records.

2018-04-12 10:47 UTC, JosiahRegencia commented
![screenshot from 2018-04-12 18-45-49](https://user-images.githubusercontent.com/8079107/38672805-e2b0d83a-3e81-11e8-904e-0221c145ee23.png)
 PASSED!
@greenmoss

2018-04-16 00:32 UTC, greenmoss commented
Excellent!

To merge this, need:
* fix conflicts
* update to only `GET`/`CREATE`, as per review

2018-04-16 09:35 UTC, JosiahRegencia commented
Fixed conflicts @greenmoss

2018-04-17 14:08 UTC, closed without merging