Issue10
Doveps/mono pull request #17
Opened 2017-08-09 14:39 UTC by JosiahRegencia

This is for issue #10

2017-08-09 22:09 UTC, JosiahRegencia commented
I also already added changes for issue #11

2017-08-10 02:22 UTC, greenmoss requested changes

2017-08-10 02:22 UTC, greenmoss commented on bassist/bassist/scripts/common.py
> +        print "requested_flavor: ", self.requested_flavor
Please remove print commands.

2017-08-10 02:22 UTC, greenmoss commented on bassist/bassist/scripts/create_flavor.py
> +            print "parser: ", parser
Please remove print commands. Also remove from line 24 and 22. You can use the logger instead.

2017-08-10 02:22 UTC, greenmoss commented on savant/app/get_scanned.py
> +	print "recording"
Please remove print commands

2017-08-10 02:22 UTC, greenmoss commented on savant/app/results.py
> +# from . import common
Please remove un-used, commented code

2017-08-10 02:22 UTC, greenmoss commented on savant/app/results.py
> +					# "Shadow" : {"New" : comparison.new_shadow()},
Please remove un-used, commented code

2017-08-10 02:22 UTC, greenmoss commented on savant/db_scripts/functions.sql
> +  SELECT id, username, password, uid, gid, description, user_path, shell
You are using 2-space indent here, but elsewhere you use tab/8-space indent

2017-08-11 05:42 UTC, JosiahRegencia commented on savant/db_scripts/functions.sql
> +  SELECT id, username, password, uid, gid, description, user_path, shell
I checked this. Not really sure what you mean. Although I note that the sql query for creating tables is 8-space indented. But for all the function queries they are only 2-space indented. I use tab automatically. Though my text editor automatically decides how many spaces for indent once I tab. Do you want it to be in uniform?

2017-08-11 21:46 UTC, greenmoss commented on savant/db_scripts/functions.sql
> +  SELECT id, username, password, uid, gid, description, user_path, shell
Yes, please make sure you use the same format. I only noticed because it changed from one indent type to the other :)

2017-08-11 21:48 UTC, greenmoss commented on savant/tests/test_basic.py
> +import unittest
This needs to go into a new Pull Request. Please target your PRs at only a single github issue.

For now, please take this out, and open a new PR.

2017-08-11 21:50 UTC, greenmoss commented on savant/tests/test_basic.py
> +import unittest
Actually, I noticed there are other commits as well. You should revert/remove everything from `6e27a89` forward, and break those into new PRs.

Next time we video chat, I'll show you why I need these split.

2017-08-12 15:37 UTC, greenmoss approved these changes

2017-08-12 15:37 UTC, merged