Flavor performance
Doveps/mono pull request #47
Opened 2017-10-07 02:10 UTC by JosiahRegencia

This is for issue #39 I uploaded in Slack the run time it took to save the data to the database. I'll remove those print codes once you approve.

2017-10-07 18:20 UTC, greenmoss requested changes

2017-10-07 18:20 UTC, greenmoss commented on savant/app/record.py
> +    print "Debs: ", debs_elapsed
Please change these print statements to `log.debug`

2017-10-07 18:20 UTC, greenmoss commented on savant/app/results.py
> +    print "Elapsed Time: ", elapsed
Same as above; please use `log.debug`

2017-10-08 05:11 UTC, JosiahRegencia commented
noticed something off when testing manually, still fixing

2017-10-08 07:27 UTC, JosiahRegencia commented
Just an update, the screenshot I showed previously wasn't really exact. Although from 32 seconds average I was able to trim it down to 10 seconds. Because of many data in debs (362 rows) it takes 8 seconds to complete. For groups (51 rows) 1 second and 0.5 seconds for shadow and users (25 rows each)

2017-10-08 08:17 UTC, JosiahRegencia commented
This last push, flavor creation performs below 1 second. I'll upload a demo later to show how fast it is.

2017-10-08 10:26 UTC, JosiahRegencia commented
Did a demo on the updated flavor performance. Here it is: https://youtu.be/WLX7IBnkOVM

2017-10-08 17:43 UTC, greenmoss approved these changes

2017-10-08 17:45 UTC, merged