Action/create
Doveps/mono pull request #51
Opened 2017-10-10 17:57 UTC by JosiahRegencia

2017-10-11 22:47 UTC, greenmoss commented
This is for #49 right?

2017-10-11 22:59 UTC, greenmoss requested changes

2017-10-11 22:59 UTC, greenmoss commented on savant/app/results.py
> +    new_packages =  json.dumps({"Debs" : {"New" : comparison.new_debs()}},
This failed the Code Climate test; can you refactor this as a single function? See https://codeclimate.com/github/Doveps/mono/pull/51

2017-10-12 02:39 UTC, JosiahRegencia commented
Yes. This is #49

2017-10-12 03:10 UTC, JosiahRegencia commented
made changes regarding the code duplication

2017-10-12 04:38 UTC, greenmoss approved these changes

2017-10-12 04:38 UTC, merged