Action/create saves to knowledge
Doveps/mono pull request #58
Opened 2017-10-30 13:51 UTC by JosiahRegencia

This is for issue #53

2017-11-01 00:57 UTC, JosiahRegencia commented
Made a demo to show you how it works. Thought it would help a lot more from reading the code and visualizing how it works. Here's the link: https://www.youtube.com/watch?v=gQvFME4q5vw&feature=youtu.be

2017-11-02 00:36 UTC, greenmoss requested changes

2017-11-02 00:36 UTC, greenmoss commented on savant/app/results.py
> -@app.route('/doveps/api/action/create/<json_file>/<name>/<resource>/<action>', methods=['GET'])
You still need to accept these parameters; see #49

2017-11-02 00:36 UTC, greenmoss commented on savant/app/query.py
> -    if resource == 'Debs':
The parameters from #49 still need to be used here.

2017-11-02 01:34 UTC, greenmoss commented on savant/app/results.py
> -@app.route('/doveps/api/action/create/<json_file>/<name>/<resource>/<action>', methods=['GET'])
When you used Vagrant to install apache2, it ran "apt-get install apache2". So for knowledge for this API request:
* name = apache2
* resource = package
* action = install

2017-11-02 01:36 UTC, greenmoss commented on savant/app/results.py
> -@app.route('/doveps/api/action/create/<json_file>/<name>/<resource>/<action>', methods=['GET'])
So in the table, you need multiple rows:
* name "apache2", resource "package", action "install", packages table id "1" (for example)
* name "apache2", resource "package", action "install", packages table id "2" (for example)
* name "apache2", resource "package", action "install", users table id "1" (for example)

2017-11-16 02:57 UTC, greenmoss commented
This is replaced by #68

2017-11-16 02:57 UTC, closed without merging