Add debs_stdouts to DB
Doveps/mono pull request #6
Opened 2017-08-01 22:24 UTC by JosiahRegencia

I made the changes to debs_stdout.py.
meaning I imported my DB queriese from savant to there.

2017-08-01 23:11 UTC, greenmoss commented
Please remove all the `*.egg_info` files, and add them to `.gitignore`

2017-08-01 23:44 UTC, greenmoss commented on bassist/bassist/parser/log_file/debs_stdout.py
>                  (stat, name, vers, arch) = parts[0:4]
This splits for you already. Instead of joining the parts and inserting the line, please insert each of these parts.

2017-08-01 23:45 UTC, greenmoss commented on bassist/bassist/flavor/db_pg.py
> +        # print object
Please remove these comments from the commit.

2017-08-01 23:46 UTC, greenmoss commented on bassist/bassist/flavor/db_pg.py
>          print "Hello db_pg"
This is a debugging statement; please either use the log command, or remove this.

2017-08-02 01:47 UTC, JosiahRegencia commented on bassist/bassist/flavor/db_pg.py
> +        # print object
I'm going to delete db_pg. I don't think I'm going to be using it anymore.

2017-08-03 01:25 UTC, greenmoss requested changes

2017-08-03 01:25 UTC, greenmoss commented on bassist/bassist/parser/log_file/debs_stdout.py
> +                print "parts: ", parts
Please remove `print` lines. OK to use them in debugging, but they shouldn't be in the committed code. If you *do* want debugging here in the final code, you should use `log` instead.

2017-08-03 01:25 UTC, greenmoss commented on bassist/bassist/parser/log_file/debs_stdout.py
> +from results import *
Please avoid using `import *`. Instead, import only what you need.

2017-08-03 01:25 UTC, greenmoss commented on .gitignore
> +flavor
This is in the base of the monorepo. Was this supposed to be in a subdirectory?

2017-08-03 17:21 UTC, JosiahRegencia commented on .gitignore
> +flavor
I'm not really sure. I just placed it anywhere and figured it wouldn't be much of a use since we're getting rid of ZODB

2017-08-03 18:21 UTC, JosiahRegencia commented
I made a mistake in my demo. I uploaded a video of the correction on Doveps Youtube channel.
Link: https://youtu.be/BZrTeZlSaz0

2017-08-04 02:38 UTC, greenmoss commented on .gitignore
> +flavor
You can either move this into the `.gitignore` in the subdirectory, or provide `full/path/to/flavor`.

2017-08-05 00:53 UTC, greenmoss requested changes

2017-08-05 00:53 UTC, greenmoss commented on savant/savant.egg-info/SOURCES.txt
> +app/__init__.py
Remove this file please

2017-08-05 00:53 UTC, greenmoss commented on savant/savant.egg-info/dependency_links.txt
> +
Remove this file please

2017-08-05 00:53 UTC, greenmoss commented on savant/savant.egg-info/top_level.txt
> +app
Remove this file please

2017-08-05 09:17 UTC, JosiahRegencia commented
I just committed issue #10

2017-08-05 13:01 UTC, zerstoeren commented
Thanks for pushing the fix video up Josiah.  It was really helpful.

:)

On Aug 3, 2017 2:21 PM, "Josiah Eleazar T. Regencia" <
notifications@github.com> wrote:

I made a mistake in my demo. I uploaded a video of the correction on Doveps
Youtube channel.
Link: https://youtu.be/BZrTeZlSaz0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Doveps/mono/pull/6#issuecomment-320050232>, or mute the
thread
<https://github.com/notifications/unsubscribe-auth/AGboggi5ooaixXDiiXlUPXu1EmJ847Omks5sUg-kgaJpZM4OqXxA>
.

2017-08-05 13:04 UTC, JosiahRegencia commented
No problem ☺

2017-08-05 15:49 UTC, greenmoss requested changes

2017-08-05 15:49 UTC, greenmoss commented on savant/run.py
> +from app import *
Please don't use `import *`. You need to call out each import individually. For instance `from app import app,thing`

2017-08-05 16:17 UTC, greenmoss approved these changes

2017-08-05 16:18 UTC, merged