Save knowledge
Doveps/mono pull request #68
Opened 2017-11-15 11:20 UTC by JosiahRegencia

this is for issue #53 

In the database, there were some blank columns. Instead of having those blank columns I replaced them with "N/A". I tried using null, but the result was that it duplicated in the tables. Going to make a demo to show how it works.

2017-11-15 16:02 UTC, JosiahRegencia commented
What's left of the issues in codeclimate are similar code issues. Which were the same ones we bypassed few meetings ago.

2017-11-16 01:40 UTC, greenmoss requested changes

2017-11-16 01:40 UTC, greenmoss commented on savant/app/get_scanned.py
> +        # for i in xrange(len(parts)):
please remove commented code

2017-11-16 01:40 UTC, greenmoss commented on savant/app/get_scanned.py
> +        # for i in xrange(len(parts)):
please remove commented code

2017-11-16 01:40 UTC, greenmoss commented on savant/app/get_scanned.py
> +        # for i in xrange(len(parts)):
please remove commented code

2017-11-16 02:51 UTC, greenmoss approved these changes

2017-11-16 02:52 UTC, merged